/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fbfbe2",
        "secondary": "#ab3600",
        "tertiary-fixed-dim": "#77dd6a",
        "on-tertiary-fixed": "#002201",
        "inverse-on-surface": "#f2f2d9",
        "on-primary-fixed-variant": "#57423e",
        "tertiary-container": "#002601",
        "primary-fixed-dim": "#dec0bb",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-low": "#f5f5dc",
        "on-background": "#1b1d0e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#390c00",
        "secondary-fixed-dim": "#ffb59c",
        "secondary-container": "#fe5e1e",
        "on-primary": "#ffffff",
        "surface-bright": "#fbfbe2",
        "primary-fixed": "#fbdcd6",
        "error": "#ba1a1a",
        "on-primary-fixed": "#281714",
        "tertiary": "#000a00",
        "on-primary-container": "#9b817c",
        "inverse-primary": "#dec0bb",
        "on-tertiary-container": "#349a30",
        "tertiary-fixed": "#92fa83",
        "on-surface-variant": "#4f4442",
        "surface-tint": "#705955",
        "on-secondary-fixed-variant": "#832700",
        "surface-dim": "#dbdcc3",
        "on-error-container": "#93000a",
        "on-secondary-container": "#551600",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e4cc",
        "primary": "#100403",
        "surface-container-highest": "#e4e4cc",
        "outline": "#817472",
        "outline-variant": "#d3c3c0",
        "primary-container": "#2c1b18",
        "on-surface": "#1b1d0e",
        "surface-container-high": "#eaead1",
        "on-tertiary-fixed-variant": "#005307",
        "surface": "#fbfbe2",
        "secondary-fixed": "#ffdbcf",
        "surface-container": "#efefd7",
        "error-container": "#ffdad6",
        "inverse-surface": "#303221"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
